"""add_type_to_tokens

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-18 23:47:25.242835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('type', sa.String(), server_default='password_reset', nullable=False))
    op.create_index(op.f('ix_tokens_type'), 'tokens', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_type'), table_name='tokens')
    op.drop_column('tokens', 'type')
    # ### end Alembic commands ###
